# Generated by Django 5.0.6 on 2024-06-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookoutchou', '0002_remove_ingredient_unit_ingredient_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='months',
            field=models.ManyToManyField(blank=True, null=True, related_name='months', to='cookoutchou.seasonalmonth'),
        ),
    ]
