# Generated by Django 5.0.6 on 2024-06-07 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookoutchou', '0003_alter_ingredient_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalmonth',
            name='number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='months',
            field=models.ManyToManyField(blank=True, related_name='months', to='cookoutchou.seasonalmonth'),
        ),
    ]
