# Generated by Django 5.0.6 on 2024-06-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookoutchou', '0004_seasonalmonth_number_alter_ingredient_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='moments',
            field=models.ManyToManyField(blank=True, related_name='moments', to='cookoutchou.moment'),
        ),
    ]
