# Generated by Django 5.0.6 on 2024-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookoutchou', '0005_alter_recipe_moments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='cookoutchou.label'),
        ),
    ]
