# Generated by Django 5.0.6 on 2024-06-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookoutchou', '0006_alter_recipe_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
